kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storageoscluster-operator-rolebinding
  labels:
    app.kubernetes.io/name: storageos-operator
    app.kubernetes.io/instance: storageos-cluster-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: storageos
subjects:
- kind: ServiceAccount
  name: storageoscluster-operator-sa
  namespace: storageos-operator
roleRef:
  kind: ClusterRole
  name: storageos-operator
  apiGroup: rbac.authorization.k8s.io
