apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageoscluster-operator-sa
  namespace: storageos-operator
  labels:
    app: storageos
    app.kubernetes.io/name: storageos-operator
    app.kubernetes.io/instance: storageos-cluster-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: storageos
